[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# This redirect ensures that all routes are handled by the index.html file
# This is important for single-page applications with client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 